/*
Tweakwise Navigator Backend API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package backend

import (
	"encoding/json"
)

// CategoryDeltaApiModel struct for CategoryDeltaApiModel
type CategoryDeltaApiModel struct {
	// 
	Name *string `json:"Name,omitempty"`
	// 
	Rank *int64 `json:"Rank,omitempty"`
	// 
	Parents *[]string `json:"Parents,omitempty"`
}

// NewCategoryDeltaApiModel instantiates a new CategoryDeltaApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryDeltaApiModel() *CategoryDeltaApiModel {
	this := CategoryDeltaApiModel{}
	return &this
}

// NewCategoryDeltaApiModelWithDefaults instantiates a new CategoryDeltaApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryDeltaApiModelWithDefaults() *CategoryDeltaApiModel {
	this := CategoryDeltaApiModel{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CategoryDeltaApiModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryDeltaApiModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CategoryDeltaApiModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CategoryDeltaApiModel) SetName(v string) {
	o.Name = &v
}

// GetRank returns the Rank field value if set, zero value otherwise.
func (o *CategoryDeltaApiModel) GetRank() int64 {
	if o == nil || o.Rank == nil {
		var ret int64
		return ret
	}
	return *o.Rank
}

// GetRankOk returns a tuple with the Rank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryDeltaApiModel) GetRankOk() (*int64, bool) {
	if o == nil || o.Rank == nil {
		return nil, false
	}
	return o.Rank, true
}

// HasRank returns a boolean if a field has been set.
func (o *CategoryDeltaApiModel) HasRank() bool {
	if o != nil && o.Rank != nil {
		return true
	}

	return false
}

// SetRank gets a reference to the given int64 and assigns it to the Rank field.
func (o *CategoryDeltaApiModel) SetRank(v int64) {
	o.Rank = &v
}

// GetParents returns the Parents field value if set, zero value otherwise.
func (o *CategoryDeltaApiModel) GetParents() []string {
	if o == nil || o.Parents == nil {
		var ret []string
		return ret
	}
	return *o.Parents
}

// GetParentsOk returns a tuple with the Parents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryDeltaApiModel) GetParentsOk() (*[]string, bool) {
	if o == nil || o.Parents == nil {
		return nil, false
	}
	return o.Parents, true
}

// HasParents returns a boolean if a field has been set.
func (o *CategoryDeltaApiModel) HasParents() bool {
	if o != nil && o.Parents != nil {
		return true
	}

	return false
}

// SetParents gets a reference to the given []string and assigns it to the Parents field.
func (o *CategoryDeltaApiModel) SetParents(v []string) {
	o.Parents = &v
}

func (o CategoryDeltaApiModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["Name"] = o.Name
	}
	if o.Rank != nil {
		toSerialize["Rank"] = o.Rank
	}
	if o.Parents != nil {
		toSerialize["Parents"] = o.Parents
	}
	return json.Marshal(toSerialize)
}

type NullableCategoryDeltaApiModel struct {
	value *CategoryDeltaApiModel
	isSet bool
}

func (v NullableCategoryDeltaApiModel) Get() *CategoryDeltaApiModel {
	return v.value
}

func (v *NullableCategoryDeltaApiModel) Set(val *CategoryDeltaApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryDeltaApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryDeltaApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryDeltaApiModel(val *CategoryDeltaApiModel) *NullableCategoryDeltaApiModel {
	return &NullableCategoryDeltaApiModel{value: val, isSet: true}
}

func (v NullableCategoryDeltaApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryDeltaApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


