/*
Tweakwise Navigator Backend API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package backend

import (
	"encoding/json"
)

// CategoryApiModel struct for CategoryApiModel
type CategoryApiModel struct {
	// 
	CategoryId *string `json:"CategoryId,omitempty"`
	// 
	Name *string `json:"Name,omitempty"`
	// 
	Rank *int64 `json:"Rank,omitempty"`
	// 
	Parents *[]string `json:"Parents,omitempty"`
}

// NewCategoryApiModel instantiates a new CategoryApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryApiModel() *CategoryApiModel {
	this := CategoryApiModel{}
	return &this
}

// NewCategoryApiModelWithDefaults instantiates a new CategoryApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryApiModelWithDefaults() *CategoryApiModel {
	this := CategoryApiModel{}
	return &this
}

// GetCategoryId returns the CategoryId field value if set, zero value otherwise.
func (o *CategoryApiModel) GetCategoryId() string {
	if o == nil || o.CategoryId == nil {
		var ret string
		return ret
	}
	return *o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryApiModel) GetCategoryIdOk() (*string, bool) {
	if o == nil || o.CategoryId == nil {
		return nil, false
	}
	return o.CategoryId, true
}

// HasCategoryId returns a boolean if a field has been set.
func (o *CategoryApiModel) HasCategoryId() bool {
	if o != nil && o.CategoryId != nil {
		return true
	}

	return false
}

// SetCategoryId gets a reference to the given string and assigns it to the CategoryId field.
func (o *CategoryApiModel) SetCategoryId(v string) {
	o.CategoryId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CategoryApiModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryApiModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CategoryApiModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CategoryApiModel) SetName(v string) {
	o.Name = &v
}

// GetRank returns the Rank field value if set, zero value otherwise.
func (o *CategoryApiModel) GetRank() int64 {
	if o == nil || o.Rank == nil {
		var ret int64
		return ret
	}
	return *o.Rank
}

// GetRankOk returns a tuple with the Rank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryApiModel) GetRankOk() (*int64, bool) {
	if o == nil || o.Rank == nil {
		return nil, false
	}
	return o.Rank, true
}

// HasRank returns a boolean if a field has been set.
func (o *CategoryApiModel) HasRank() bool {
	if o != nil && o.Rank != nil {
		return true
	}

	return false
}

// SetRank gets a reference to the given int64 and assigns it to the Rank field.
func (o *CategoryApiModel) SetRank(v int64) {
	o.Rank = &v
}

// GetParents returns the Parents field value if set, zero value otherwise.
func (o *CategoryApiModel) GetParents() []string {
	if o == nil || o.Parents == nil {
		var ret []string
		return ret
	}
	return *o.Parents
}

// GetParentsOk returns a tuple with the Parents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryApiModel) GetParentsOk() (*[]string, bool) {
	if o == nil || o.Parents == nil {
		return nil, false
	}
	return o.Parents, true
}

// HasParents returns a boolean if a field has been set.
func (o *CategoryApiModel) HasParents() bool {
	if o != nil && o.Parents != nil {
		return true
	}

	return false
}

// SetParents gets a reference to the given []string and assigns it to the Parents field.
func (o *CategoryApiModel) SetParents(v []string) {
	o.Parents = &v
}

func (o CategoryApiModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CategoryId != nil {
		toSerialize["CategoryId"] = o.CategoryId
	}
	if o.Name != nil {
		toSerialize["Name"] = o.Name
	}
	if o.Rank != nil {
		toSerialize["Rank"] = o.Rank
	}
	if o.Parents != nil {
		toSerialize["Parents"] = o.Parents
	}
	return json.Marshal(toSerialize)
}

type NullableCategoryApiModel struct {
	value *CategoryApiModel
	isSet bool
}

func (v NullableCategoryApiModel) Get() *CategoryApiModel {
	return v.value
}

func (v *NullableCategoryApiModel) Set(val *CategoryApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryApiModel(val *CategoryApiModel) *NullableCategoryApiModel {
	return &NullableCategoryApiModel{value: val, isSet: true}
}

func (v NullableCategoryApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


