/*
Tweakwise Navigator Backend API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package backend

import (
	"encoding/json"
)

// Product struct for Product
type Product struct {
	ArticleNumber *string `json:"ArticleNumber,omitempty"`
	Name *string `json:"Name,omitempty"`
	Price *float64 `json:"Price,omitempty"`
	Brand *string `json:"Brand,omitempty"`
	Stock *int32 `json:"Stock,omitempty"`
	GroupCode *string `json:"GroupCode,omitempty"`
	Image *string `json:"Image,omitempty"`
	Url *string `json:"Url,omitempty"`
	Categories *[]int64 `json:"Categories,omitempty"`
	Attributes *[]ProductAttribute `json:"Attributes,omitempty"`
}

// NewProduct instantiates a new Product object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct() *Product {
	this := Product{}
	return &this
}

// NewProductWithDefaults instantiates a new Product object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductWithDefaults() *Product {
	this := Product{}
	return &this
}

// GetArticleNumber returns the ArticleNumber field value if set, zero value otherwise.
func (o *Product) GetArticleNumber() string {
	if o == nil || o.ArticleNumber == nil {
		var ret string
		return ret
	}
	return *o.ArticleNumber
}

// GetArticleNumberOk returns a tuple with the ArticleNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetArticleNumberOk() (*string, bool) {
	if o == nil || o.ArticleNumber == nil {
		return nil, false
	}
	return o.ArticleNumber, true
}

// HasArticleNumber returns a boolean if a field has been set.
func (o *Product) HasArticleNumber() bool {
	if o != nil && o.ArticleNumber != nil {
		return true
	}

	return false
}

// SetArticleNumber gets a reference to the given string and assigns it to the ArticleNumber field.
func (o *Product) SetArticleNumber(v string) {
	o.ArticleNumber = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Product) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Product) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Product) SetName(v string) {
	o.Name = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *Product) GetPrice() float64 {
	if o == nil || o.Price == nil {
		var ret float64
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetPriceOk() (*float64, bool) {
	if o == nil || o.Price == nil {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *Product) HasPrice() bool {
	if o != nil && o.Price != nil {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float64 and assigns it to the Price field.
func (o *Product) SetPrice(v float64) {
	o.Price = &v
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *Product) GetBrand() string {
	if o == nil || o.Brand == nil {
		var ret string
		return ret
	}
	return *o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetBrandOk() (*string, bool) {
	if o == nil || o.Brand == nil {
		return nil, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *Product) HasBrand() bool {
	if o != nil && o.Brand != nil {
		return true
	}

	return false
}

// SetBrand gets a reference to the given string and assigns it to the Brand field.
func (o *Product) SetBrand(v string) {
	o.Brand = &v
}

// GetStock returns the Stock field value if set, zero value otherwise.
func (o *Product) GetStock() int32 {
	if o == nil || o.Stock == nil {
		var ret int32
		return ret
	}
	return *o.Stock
}

// GetStockOk returns a tuple with the Stock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetStockOk() (*int32, bool) {
	if o == nil || o.Stock == nil {
		return nil, false
	}
	return o.Stock, true
}

// HasStock returns a boolean if a field has been set.
func (o *Product) HasStock() bool {
	if o != nil && o.Stock != nil {
		return true
	}

	return false
}

// SetStock gets a reference to the given int32 and assigns it to the Stock field.
func (o *Product) SetStock(v int32) {
	o.Stock = &v
}

// GetGroupCode returns the GroupCode field value if set, zero value otherwise.
func (o *Product) GetGroupCode() string {
	if o == nil || o.GroupCode == nil {
		var ret string
		return ret
	}
	return *o.GroupCode
}

// GetGroupCodeOk returns a tuple with the GroupCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetGroupCodeOk() (*string, bool) {
	if o == nil || o.GroupCode == nil {
		return nil, false
	}
	return o.GroupCode, true
}

// HasGroupCode returns a boolean if a field has been set.
func (o *Product) HasGroupCode() bool {
	if o != nil && o.GroupCode != nil {
		return true
	}

	return false
}

// SetGroupCode gets a reference to the given string and assigns it to the GroupCode field.
func (o *Product) SetGroupCode(v string) {
	o.GroupCode = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *Product) GetImage() string {
	if o == nil || o.Image == nil {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetImageOk() (*string, bool) {
	if o == nil || o.Image == nil {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *Product) HasImage() bool {
	if o != nil && o.Image != nil {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *Product) SetImage(v string) {
	o.Image = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Product) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Product) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Product) SetUrl(v string) {
	o.Url = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *Product) GetCategories() []int64 {
	if o == nil || o.Categories == nil {
		var ret []int64
		return ret
	}
	return *o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetCategoriesOk() (*[]int64, bool) {
	if o == nil || o.Categories == nil {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *Product) HasCategories() bool {
	if o != nil && o.Categories != nil {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []int64 and assigns it to the Categories field.
func (o *Product) SetCategories(v []int64) {
	o.Categories = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *Product) GetAttributes() []ProductAttribute {
	if o == nil || o.Attributes == nil {
		var ret []ProductAttribute
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetAttributesOk() (*[]ProductAttribute, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *Product) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []ProductAttribute and assigns it to the Attributes field.
func (o *Product) SetAttributes(v []ProductAttribute) {
	o.Attributes = &v
}

func (o Product) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ArticleNumber != nil {
		toSerialize["ArticleNumber"] = o.ArticleNumber
	}
	if o.Name != nil {
		toSerialize["Name"] = o.Name
	}
	if o.Price != nil {
		toSerialize["Price"] = o.Price
	}
	if o.Brand != nil {
		toSerialize["Brand"] = o.Brand
	}
	if o.Stock != nil {
		toSerialize["Stock"] = o.Stock
	}
	if o.GroupCode != nil {
		toSerialize["GroupCode"] = o.GroupCode
	}
	if o.Image != nil {
		toSerialize["Image"] = o.Image
	}
	if o.Url != nil {
		toSerialize["Url"] = o.Url
	}
	if o.Categories != nil {
		toSerialize["Categories"] = o.Categories
	}
	if o.Attributes != nil {
		toSerialize["Attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableProduct struct {
	value *Product
	isSet bool
}

func (v NullableProduct) Get() *Product {
	return v.value
}

func (v *NullableProduct) Set(val *Product) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct(val *Product) *NullableProduct {
	return &NullableProduct{value: val, isSet: true}
}

func (v NullableProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


