/*
Tweakwise Navigator Backend API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package backend

import (
	"encoding/json"
)

// ProductAttribute struct for ProductAttribute
type ProductAttribute struct {
	Key *string `json:"Key,omitempty"`
	Values *[]string `json:"Values,omitempty"`
}

// NewProductAttribute instantiates a new ProductAttribute object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductAttribute() *ProductAttribute {
	this := ProductAttribute{}
	return &this
}

// NewProductAttributeWithDefaults instantiates a new ProductAttribute object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductAttributeWithDefaults() *ProductAttribute {
	this := ProductAttribute{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ProductAttribute) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductAttribute) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ProductAttribute) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ProductAttribute) SetKey(v string) {
	o.Key = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *ProductAttribute) GetValues() []string {
	if o == nil || o.Values == nil {
		var ret []string
		return ret
	}
	return *o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductAttribute) GetValuesOk() (*[]string, bool) {
	if o == nil || o.Values == nil {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *ProductAttribute) HasValues() bool {
	if o != nil && o.Values != nil {
		return true
	}

	return false
}

// SetValues gets a reference to the given []string and assigns it to the Values field.
func (o *ProductAttribute) SetValues(v []string) {
	o.Values = &v
}

func (o ProductAttribute) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Key != nil {
		toSerialize["Key"] = o.Key
	}
	if o.Values != nil {
		toSerialize["Values"] = o.Values
	}
	return json.Marshal(toSerialize)
}

type NullableProductAttribute struct {
	value *ProductAttribute
	isSet bool
}

func (v NullableProductAttribute) Get() *ProductAttribute {
	return v.value
}

func (v *NullableProductAttribute) Set(val *ProductAttribute) {
	v.value = val
	v.isSet = true
}

func (v NullableProductAttribute) IsSet() bool {
	return v.isSet
}

func (v *NullableProductAttribute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductAttribute(val *ProductAttribute) *NullableProductAttribute {
	return &NullableProductAttribute{value: val, isSet: true}
}

func (v NullableProductAttribute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductAttribute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


