/*
Tweakwise Navigator Backend API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package backend

import (
	"encoding/json"
)

// ActiveChannelModel ActiveChannelModel
type ActiveChannelModel struct {
	// ChannelID
	ChannelId string `json:"ChannelId"`
}

// NewActiveChannelModel instantiates a new ActiveChannelModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActiveChannelModel(channelId string) *ActiveChannelModel {
	this := ActiveChannelModel{}
	this.ChannelId = channelId
	return &this
}

// NewActiveChannelModelWithDefaults instantiates a new ActiveChannelModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActiveChannelModelWithDefaults() *ActiveChannelModel {
	this := ActiveChannelModel{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *ActiveChannelModel) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *ActiveChannelModel) GetChannelIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *ActiveChannelModel) SetChannelId(v string) {
	o.ChannelId = v
}

func (o ActiveChannelModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ChannelId"] = o.ChannelId
	}
	return json.Marshal(toSerialize)
}

type NullableActiveChannelModel struct {
	value *ActiveChannelModel
	isSet bool
}

func (v NullableActiveChannelModel) Get() *ActiveChannelModel {
	return v.value
}

func (v *NullableActiveChannelModel) Set(val *ActiveChannelModel) {
	v.value = val
	v.isSet = true
}

func (v NullableActiveChannelModel) IsSet() bool {
	return v.isSet
}

func (v *NullableActiveChannelModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActiveChannelModel(val *ActiveChannelModel) *NullableActiveChannelModel {
	return &NullableActiveChannelModel{value: val, isSet: true}
}

func (v NullableActiveChannelModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActiveChannelModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


