/*
Tweakwise Navigator Backend API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package backend

import (
	"encoding/json"
)

// ProductDeltaApiModel struct for ProductDeltaApiModel
type ProductDeltaApiModel struct {
	Name *string `json:"Name,omitempty"`
	Price *float64 `json:"Price,omitempty"`
	Brand *string `json:"Brand,omitempty"`
	Stock *int32 `json:"Stock,omitempty"`
	GroupCode *string `json:"GroupCode,omitempty"`
	Image *string `json:"Image,omitempty"`
	Url *string `json:"Url,omitempty"`
	Categories *[]string `json:"Categories,omitempty"`
	Attributes *[]ProductAttributeApiModel `json:"Attributes,omitempty"`
}

// NewProductDeltaApiModel instantiates a new ProductDeltaApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductDeltaApiModel() *ProductDeltaApiModel {
	this := ProductDeltaApiModel{}
	return &this
}

// NewProductDeltaApiModelWithDefaults instantiates a new ProductDeltaApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductDeltaApiModelWithDefaults() *ProductDeltaApiModel {
	this := ProductDeltaApiModel{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProductDeltaApiModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDeltaApiModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProductDeltaApiModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProductDeltaApiModel) SetName(v string) {
	o.Name = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *ProductDeltaApiModel) GetPrice() float64 {
	if o == nil || o.Price == nil {
		var ret float64
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDeltaApiModel) GetPriceOk() (*float64, bool) {
	if o == nil || o.Price == nil {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *ProductDeltaApiModel) HasPrice() bool {
	if o != nil && o.Price != nil {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float64 and assigns it to the Price field.
func (o *ProductDeltaApiModel) SetPrice(v float64) {
	o.Price = &v
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *ProductDeltaApiModel) GetBrand() string {
	if o == nil || o.Brand == nil {
		var ret string
		return ret
	}
	return *o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDeltaApiModel) GetBrandOk() (*string, bool) {
	if o == nil || o.Brand == nil {
		return nil, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *ProductDeltaApiModel) HasBrand() bool {
	if o != nil && o.Brand != nil {
		return true
	}

	return false
}

// SetBrand gets a reference to the given string and assigns it to the Brand field.
func (o *ProductDeltaApiModel) SetBrand(v string) {
	o.Brand = &v
}

// GetStock returns the Stock field value if set, zero value otherwise.
func (o *ProductDeltaApiModel) GetStock() int32 {
	if o == nil || o.Stock == nil {
		var ret int32
		return ret
	}
	return *o.Stock
}

// GetStockOk returns a tuple with the Stock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDeltaApiModel) GetStockOk() (*int32, bool) {
	if o == nil || o.Stock == nil {
		return nil, false
	}
	return o.Stock, true
}

// HasStock returns a boolean if a field has been set.
func (o *ProductDeltaApiModel) HasStock() bool {
	if o != nil && o.Stock != nil {
		return true
	}

	return false
}

// SetStock gets a reference to the given int32 and assigns it to the Stock field.
func (o *ProductDeltaApiModel) SetStock(v int32) {
	o.Stock = &v
}

// GetGroupCode returns the GroupCode field value if set, zero value otherwise.
func (o *ProductDeltaApiModel) GetGroupCode() string {
	if o == nil || o.GroupCode == nil {
		var ret string
		return ret
	}
	return *o.GroupCode
}

// GetGroupCodeOk returns a tuple with the GroupCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDeltaApiModel) GetGroupCodeOk() (*string, bool) {
	if o == nil || o.GroupCode == nil {
		return nil, false
	}
	return o.GroupCode, true
}

// HasGroupCode returns a boolean if a field has been set.
func (o *ProductDeltaApiModel) HasGroupCode() bool {
	if o != nil && o.GroupCode != nil {
		return true
	}

	return false
}

// SetGroupCode gets a reference to the given string and assigns it to the GroupCode field.
func (o *ProductDeltaApiModel) SetGroupCode(v string) {
	o.GroupCode = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *ProductDeltaApiModel) GetImage() string {
	if o == nil || o.Image == nil {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDeltaApiModel) GetImageOk() (*string, bool) {
	if o == nil || o.Image == nil {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *ProductDeltaApiModel) HasImage() bool {
	if o != nil && o.Image != nil {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *ProductDeltaApiModel) SetImage(v string) {
	o.Image = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ProductDeltaApiModel) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDeltaApiModel) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ProductDeltaApiModel) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ProductDeltaApiModel) SetUrl(v string) {
	o.Url = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *ProductDeltaApiModel) GetCategories() []string {
	if o == nil || o.Categories == nil {
		var ret []string
		return ret
	}
	return *o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDeltaApiModel) GetCategoriesOk() (*[]string, bool) {
	if o == nil || o.Categories == nil {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *ProductDeltaApiModel) HasCategories() bool {
	if o != nil && o.Categories != nil {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []string and assigns it to the Categories field.
func (o *ProductDeltaApiModel) SetCategories(v []string) {
	o.Categories = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *ProductDeltaApiModel) GetAttributes() []ProductAttributeApiModel {
	if o == nil || o.Attributes == nil {
		var ret []ProductAttributeApiModel
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDeltaApiModel) GetAttributesOk() (*[]ProductAttributeApiModel, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *ProductDeltaApiModel) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []ProductAttributeApiModel and assigns it to the Attributes field.
func (o *ProductDeltaApiModel) SetAttributes(v []ProductAttributeApiModel) {
	o.Attributes = &v
}

func (o ProductDeltaApiModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["Name"] = o.Name
	}
	if o.Price != nil {
		toSerialize["Price"] = o.Price
	}
	if o.Brand != nil {
		toSerialize["Brand"] = o.Brand
	}
	if o.Stock != nil {
		toSerialize["Stock"] = o.Stock
	}
	if o.GroupCode != nil {
		toSerialize["GroupCode"] = o.GroupCode
	}
	if o.Image != nil {
		toSerialize["Image"] = o.Image
	}
	if o.Url != nil {
		toSerialize["Url"] = o.Url
	}
	if o.Categories != nil {
		toSerialize["Categories"] = o.Categories
	}
	if o.Attributes != nil {
		toSerialize["Attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableProductDeltaApiModel struct {
	value *ProductDeltaApiModel
	isSet bool
}

func (v NullableProductDeltaApiModel) Get() *ProductDeltaApiModel {
	return v.value
}

func (v *NullableProductDeltaApiModel) Set(val *ProductDeltaApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableProductDeltaApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableProductDeltaApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductDeltaApiModel(val *ProductDeltaApiModel) *NullableProductDeltaApiModel {
	return &NullableProductDeltaApiModel{value: val, isSet: true}
}

func (v NullableProductDeltaApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductDeltaApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


