/*
Tweakwise Navigator Backend API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package backend

import (
	"encoding/json"
)

// SalesChannel Shopware 6 sales channel
type SalesChannel struct {
	// Sales channel id
	Id *string `json:"Id,omitempty"`
	// Sales channel name
	Name *string `json:"Name,omitempty"`
}

// NewSalesChannel instantiates a new SalesChannel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSalesChannel() *SalesChannel {
	this := SalesChannel{}
	return &this
}

// NewSalesChannelWithDefaults instantiates a new SalesChannel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSalesChannelWithDefaults() *SalesChannel {
	this := SalesChannel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SalesChannel) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesChannel) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SalesChannel) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SalesChannel) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SalesChannel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesChannel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SalesChannel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SalesChannel) SetName(v string) {
	o.Name = &v
}

func (o SalesChannel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["Id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["Name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableSalesChannel struct {
	value *SalesChannel
	isSet bool
}

func (v NullableSalesChannel) Get() *SalesChannel {
	return v.value
}

func (v *NullableSalesChannel) Set(val *SalesChannel) {
	v.value = val
	v.isSet = true
}

func (v NullableSalesChannel) IsSet() bool {
	return v.isSet
}

func (v *NullableSalesChannel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSalesChannel(val *SalesChannel) *NullableSalesChannel {
	return &NullableSalesChannel{value: val, isSet: true}
}

func (v NullableSalesChannel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSalesChannel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


