/*
Tweakwise Navigator Backend API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package backend

import (
	"encoding/json"
)

// ProductAttributeApiModel struct for ProductAttributeApiModel
type ProductAttributeApiModel struct {
	Key *string `json:"Key,omitempty"`
	Values *[]string `json:"Values,omitempty"`
}

// NewProductAttributeApiModel instantiates a new ProductAttributeApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductAttributeApiModel() *ProductAttributeApiModel {
	this := ProductAttributeApiModel{}
	return &this
}

// NewProductAttributeApiModelWithDefaults instantiates a new ProductAttributeApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductAttributeApiModelWithDefaults() *ProductAttributeApiModel {
	this := ProductAttributeApiModel{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ProductAttributeApiModel) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductAttributeApiModel) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ProductAttributeApiModel) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ProductAttributeApiModel) SetKey(v string) {
	o.Key = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *ProductAttributeApiModel) GetValues() []string {
	if o == nil || o.Values == nil {
		var ret []string
		return ret
	}
	return *o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductAttributeApiModel) GetValuesOk() (*[]string, bool) {
	if o == nil || o.Values == nil {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *ProductAttributeApiModel) HasValues() bool {
	if o != nil && o.Values != nil {
		return true
	}

	return false
}

// SetValues gets a reference to the given []string and assigns it to the Values field.
func (o *ProductAttributeApiModel) SetValues(v []string) {
	o.Values = &v
}

func (o ProductAttributeApiModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Key != nil {
		toSerialize["Key"] = o.Key
	}
	if o.Values != nil {
		toSerialize["Values"] = o.Values
	}
	return json.Marshal(toSerialize)
}

type NullableProductAttributeApiModel struct {
	value *ProductAttributeApiModel
	isSet bool
}

func (v NullableProductAttributeApiModel) Get() *ProductAttributeApiModel {
	return v.value
}

func (v *NullableProductAttributeApiModel) Set(val *ProductAttributeApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableProductAttributeApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableProductAttributeApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductAttributeApiModel(val *ProductAttributeApiModel) *NullableProductAttributeApiModel {
	return &NullableProductAttributeApiModel{value: val, isSet: true}
}

func (v NullableProductAttributeApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductAttributeApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


